### ISSUE TITLE
Incorrect parsing of type complex fields

### ISSUE THREAD

**Issue by oleg-dev** [openlayers/jsdoc-plugin-typescript#27]
If we try to describe type field, which is, in fact, field of another type. For example `product: Product['id']`, plugin doesn't parse this syntax.
We can use just a simple type, like a `product: string`, but previous syntax is more clear for readable.

Example of types:
```
/**
 * Product type description
 * @typedef Product
 */
export type Product = {
  id: string,
  name: string,
}

/**
 * Account type description
 * @typedef Account
 */
export type Account = {
  id: string,
  name: string,
  product: Product['id'],
}
```

**Comment by ahocevar** [comment]
And how were you trying to express this in JSDoc? Note that jsdoc-plugin-typescript does not make sense in a context like the above, where you define the type in TypeScript. That's not what it was made for. It was made for JSDoc annotated JavaScript.

**Comment by oleg-dev** [comment]
Yes. Thank you for answer.
Hovewer I don't want to JSDoc handling this case for documentation. I just want to avoid parsing error during documentation generation by the simplest way, as it can be fixed.

**Comment by ahocevar** [comment]
But where do you get a parsing error with the above code? The comments do not contain anything the plugin cannot parse, and it does not try to parse anything beyond the comments.

**Comment by oleg-dev** [comment]
I face with error from jsdoc, because of unsupported syntax. I am not sure, if this case can be covered by jsdoc-plugin-typescript, but if it possible, I will be very thankfull.
Error is next:

> jsdoc -c jsdoc.json

ERROR: Unable to parse a tag's type expression for source file /Users/______/_____________/src/store/modules/home.ts in line 47 with tag title "getter" and text "{Product['id']} availableProducts=customProducts Returns changes of products, made by user": Invalid type expression "Product['id']": Expected "!", "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "[" found.

**Comment by ahocevar** [comment]
How would you convert that type to something that JSDoc understands? `Product.id`?

**Comment by oleg-dev** [comment]
Excuse me, if I am not obviosuly understandable correctly about requirements, that I needed.
I just write Product['id'] in field type, but in fact I can write type 'string'. Hovewer, Product['id'] is more clear for code readability. 

The quicklier ways, from my perspective to parse the type by plugin as just 'string', because Product['id'] has string type, or maybe Product.id

**Comment by oleg-dev** [comment]
@ahocevar could you write please, if it's possible to fix this issue?

**Comment by ahocevar** [comment]
Probably not. You could, however, define your type differently:
```js

/** @typedef {string} ProductId */

/**
 * Product type description
 * @typedef {Object} Product
 * @property {ProductId} id
 * @property {string} name
 */

/**
 * Account type description
 * @typedef {Object} Account
 * @property {string} id
 * @property {string} name
 * @property {ProductId} product
 */

**Comment by oleg-dev** [comment]
@ahocevar Thank you, very much. As you proposed above, I use syntax Product.id. It disables click by type in jsdoc dist documentation. Hovewer, it's not so critical for me. That's why it's a easiest fix for my case.
Thank you for you help and advice!
I think, the issue can be closed
